version: "3.8"

volumes:
  vol-emqx-data:
    name: foo-emqx-data
  vol-emqx-etc:
    name: foo-emqx-etc
  vol-emqx-log:
    name: foo-emqx-log

  mongodb:

networks:
  internal:
  web:
    name: nginx_web
    external: true

services:
  mongodb:
    container_name: mongodb
    image: mongo:6.0.5
    restart: always
    expose:
      - ${MONGO_EXT_PORT}
    volumes:
      - mongodb:/data/db
    ports:
      - ${MONGO_EXT_PORT}:27017
    environment:
      TZ: ${TZ}
      MONGO_INITDB_DATABASE: ${MONGO_NAME_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - internal

  emqx:
    container_name: emqx
    image: emqx/emqx:4.4.19
    depends_on:
      - mongodb
    restart: always
    ports:
      - 18083:18083
      - 18084:18084
      - 1883:1883
      - 8883:8883
      - 8083:8083
      - 8084:8084
      - 8085:8081

    volumes:
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-etc:/opt/emqx/etc
      - vol-emqx-log:/opt/emqx/log
      - ./nginx/production/certbot/conf:/opt/emqx/etc/letsencrypt

    environment:
      TZ: ${TZ}
      EMQX_NAME: antel-iot
      EMQX_HOST: 127.0.0.1

      EMQX_DASHBOARD__DEFAULT_USER__PASSWORD: ${EMQX_DEFAULT_USER_PASSWORD}
      EMQX_MANAGEMENT__DEFAULT_APPLICATION__SECRET: ${EMQX_DEFAULT_APPLICATION_SECRET}

      EMQX_ALLOW_ANONYMOUS: "false"
      EMQX_NOMATCH: "deny"

      # MONGO CONNECTION
      EMQX_AUTH__MONGO__TYPE: single
      EMQX_AUTH__MONGO__TOPOLOGY__POOL_SIZE: 1
      EMQX_AUTH__MONGO__TOPOLOGY__MAX_OVERFLOW: 0

      EMQX_AUTH__MONGO__SERVER: "mongodb:${MONGO_EXT_PORT}"
      EMQX_AUTH__MONGO__POOL: 8

      EMQX_AUTH__MONGO__LOGIN: ${MONGO_USERNAME}
      EMQX_AUTH__MONGO__PASSWORD: ${MONGO_PASSWORD}
      EMQX_AUTH__MONGO__AUTH_SOURCE: admin

      EMQX_AUTH__MONGO__DATABASE: ${MONGO_NAME_DB}
      EMQX_AUTH__MONGO__AUTH_QUERY__COLLECTION: "emqxauthrules"

      EMQX_AUTH__MONGO__SUPER_QUERY__COLLECTION: "emqxauthrules"
      EMQX_AUTH__MONGO__SUPER_QUERY__SUPER_FIELD: "is_superuser"
      EMQX_AUTH__MONGO__SUPER_QUERY__SELECTOR: "username=%u"
      EMQX_AUTH__MONGO__SUPER_QUERY: "off"

      EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_HASH: plain
      EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_FIELD: "password"
      EMQX_AUTH__MONGO__AUTH_QUERY__SELECTOR: "username=%u"

      # ENABLE ACL QUERY
      EMQX_AUTH__MONGO__ACL_QUERY: "on"
      EMQX_AUTH__MONGO__ACL_QUERY__COLLECTION: "emqxauthrules"
      EMQX_AUTH__MONGO__ACL_QUERY__SELECTOR: "username=%u"

      # CONFIG DASHBOARD
      EMQX_DASHBOARD__LISTENER__HTTPS: 18084
      EMQX_DASHBOARD__LISTENER__HTTPS__ACCEPTORS: 2
      EMQX_DASHBOARD__LISTENER__HTTPS__MAX_CLIENTS: 2
      EMQX_DASHBOARD__LISTENER__HTTPS__KEYFILE: "etc/certs/key.pem"
      EMQX_DASHBOARD__LISTENER__HTTPS__CERTFILE: "etc/certs/cert.pem"
      EMQX_DASHBOARD__LISTENER__HTTP__MAX_CLIENTS: 2

      # CONFIG MANAGEMENT
      EMQX_MANAGEMENT__LISTENER_HTTPS__CERTFILE: "etc/certs/cert.pem"
      EMQX_MANAGEMENT__LISTENER_HTTPS__KEYFILE: "etc/certs/key.pem"

      # RESTRICTIONS
      EMQX_LISTENER__TCP__EXTERNAL__MAX_CONNECTIONS: 1000
      EMQX_LISTENER__SSL__EXTERNAL__MAX_CONNECTIONS: 1000
      EMQX_LISTENER__WS__EXTERNAL__MAX_CONNECTIONS: 1000
      EMQX_LISTENER__WSS__EXTERNAL__MAX_CONNECTIONS: 1000

      EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_mongo"

    networks:
      - internal
      - web

  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mongodb
      - emqx
    restart: always
    expose:
      - 5000
    env_file:
      - ./backend/.production.env
    command: "npm run start:prod"
    networks:
      - internal
      - web

  nuxt:
    container_name: nuxt
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - api
    restart: always
    expose:
      - 3000
    env_file:
      - ./frontend/.env
    command: "npm run start"
    networks:
      - internal
      - web
