export * from "./device.interface";
export * from "./template.interface";
export * from "./widgetconfig.interface";
export * from "./user.interface";
export * from "./auth.interface";
export * from "./loggedUser.interface";
export * from "./alarm.interface";
export * from "./notificacion.interface";
export * from "./toSendMqtt.interface";
